### ISSUE TITLE
对更改容器存储位置的疑问

### ISSUE THREAD

**Issue by GeekDream-x** [datawhalechina/team-learning-program#4]
教程中对于更改docker镜像存储位置的方法，提了三种。其中第二种是指定容器启动参数。请问教程中上边说CentOS中配置文件是/etc/sysconfig/docker， 为什么下面用vi进行更改的时候打开的是/usr/lib/systemd/system/docker.service 呢？

![2111618408031_ pic](https://user-images.githubusercontent.com/52285873/114849116-08d97100-9e12-11eb-8b17-9a7849254f88.jpg)

谢谢~

**Comment by lychjck** [comment]
[是/usr/lib里的docker引用了sysconfig里面的配置文件
![微信图片_20210416172447](https://user-images.githubusercontent.com/33904267/115003824-c169e800-9ed8-11eb-920c-c1164f8e38df.png)
准确的说是引用了sysconfig里的文件，然后sysconfig里的文件有OPTION这个变量,所以是可以直接添加的

**Comment by SuperSupeng** [comment]
1.
