### ISSUE TITLE
task5 示例的 compose 应用可以进入服务吗

### ISSUE THREAD

**Issue by mba1398** [datawhalechina/team-learning-program#6]
task5 示例的 compose 应用（刷新页面那个）可以进入服务吗？
命令是什么呢？

**Comment by SuperSupeng** [comment]
没太理解你说的进入服务是指什么

**Comment by mba1398** [comment]
就是这部分内容
https://github.com/datawhalechina/team-learning-program/blob/master/Docker/05%20Docker%20Compose.md#%E8%BF%9B%E5%85%A5%E6%9C%8D%E5%8A%A1

**Comment by SuperSupeng** [comment]
通过docker-compose exec web bash就可以进入web容器的内部。进入redis内部的话就将web替换为redis即可。

**Comment by mba1398** [comment]
还不没搞懂（捂脸。。。
![20210420221937](https://user-images.githubusercontent.com/26516464/115412183-aecc1780-a226-11eb-9dfe-f8991d42a000.jpg)

**Comment by SuperSupeng** [comment]
那试一下 docker-compose exec web /bin/bash呢

**Comment by mba1398** [comment]
还是不行，有时间的话，回头你试试吧

**Comment by SuperSupeng** [comment]
我这试了 是可以的 不太清楚你那里具体出了什么问题
